version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=mysecret
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
    command: npm start

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
